services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
    volumes:
      - ${APP_DIR:?err}/sonarr/config:/config
      - ${DATA_DIR:?err}:/data
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
