# TorGuard WireGuard Config
[Interface]
PrivateKey = WLbXldyAA1s7in4zeWYQVxWoR1ODf8g9w8XeNxWxp18=
ListenPort = 52293
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.10.217/24

[Peer]
PublicKey = h23MEU9YNct417qbFmfuvs13zPifqUC+NSN3CmpL3Fk=
AllowedIPs = 0.0.0.0/0
Endpoint = 146.70.51.138:1443
PersistentKeepalive = 25