services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
    volumes:
      - ${APP_DIR:?err}/prowlarr/config:/config
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
