services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    devices: 
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - VERSION=docker
    volumes:
      - ${APP_DIR:?err}/plex/config:/config
      - ${DATA_DIR:?err}/media/tv:/tv
      - ${DATA_DIR:?err}/media/movies:/movies

