services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - VERSION=docker
    volumes:
      - ${APP_DIR:?err}/plex/config:/config
      - ${DATA_DIR:?err}/media/tv:/tv
      - ${DATA_DIR:?err}/media/movies:/movies
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
