services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - VERSION=docker
    volumes:
      - ${APP_DIR:?err}/plex/config:/config
      - ${DATA_DIR:?err}/media/tv:/tv
      - ${DATA_DIR:?err}/media/movies:/movies
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
