# https://github.com/dani-garcia/vaultwarden
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 8687:80
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
    volumes:
      - ${APP_DIR:?err}/vaultwarden/data:/data
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
